// <auto-generated />
using System;
using EntityFrameworkMatReview;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkMatReview.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220303105753_locker")]
    partial class locker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkMatReview.Models.Locker", b =>
                {
                    b.Property<int>("LockerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("LockerId");

                    b.HasIndex("StudentId");

                    b.ToTable("Locker");
                });

            modelBuilder.Entity("EntityFrameworkMatReview.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("EntityFrameworkMatReview.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PetId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("PetId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EntityFrameworkMatReview.Models.Locker", b =>
                {
                    b.HasOne("EntityFrameworkMatReview.Models.Student", null)
                        .WithMany("Lockers")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("EntityFrameworkMatReview.Models.Student", b =>
                {
                    b.HasOne("EntityFrameworkMatReview.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");
                });
#pragma warning restore 612, 618
        }
    }
}
